### ISSUE TITLE
Running action on ubuntu-latest returns error "email not set"

### ISSUE THREAD

**Issue by SimonDarksideJ** [tool3/docsify-action#135]
Running the job with the yaml described on the front page simply results in the following error

> Error: Failed to publish Cannot read property 'email' of undefined

Any ideas on how to resolve?

I tried adding a powershell script to set the git username / email environment settings but it did not resolve the issue

**Comment by tool3** [comment]
hey @SimonDarksideJ I just tried it and it works.

are you talking about `docsify-action` or `publisher` ? :)

**Comment by calston** [comment]
Does not work for me either

`Error: Failed to publish Cannot read property 'email' of undefined`

**Comment by tool3** [comment]
@SimonDarksideJ @calston I verified the issue and fixed it (I think 🙄).
can you please test with `@tool3/docsify-action@master` ?  Thanks !

**Comment by calston** [comment]
That did the trick, thank you for the wonderful service :D

**Comment by tool3** [comment]
@calston Anytime! Thanks for using my action! 🤘🏻
